'use strict';
const $=s=>document.querySelector(s), key='xince-payroll-v1';
const money=n=>'¥ '+(n/100).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
const escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={version:1,members:[],months:{}},view='payroll',editing=null;
function validState(s){return s&&s.version===1&&Array.isArray(s.members)&&s.members.every(m=>m&&typeof m.id==='string'&&typeof m.name==='string'&&m.name.trim()&&['phone','identity','bank'].every(k=>typeof m[k]==='string')&&['receiverBank','routing','accountName'].every(k=>m[k]===undefined||typeof m[k]==='string'))&&new Set(s.members.map(m=>m.id)).size===s.members.length&&(!s.bankSettings||['payerBank','payerAccount','payerName'].every(k=>typeof s.bankSettings[k]==='string'))&&s.months&&typeof s.months==='object'&&!Array.isArray(s.months)&&Object.entries(s.months).every(([month,records])=>/^\d{4}-(0[1-9]|1[0-2])$/.test(month)&&records&&typeof records==='object'&&Object.entries(records).every(([id,r])=>s.members.some(m=>m.id===id)&&r&&Number.isFinite(r.days)&&r.days>=0&&r.days<=31&&typeof r.paid==='boolean'&&typeof r.note==='string'&&['projects','milestones'].every(k=>Array.isArray(r[k])&&r[k].every(a=>a&&typeof a.name==='string'&&a.name.trim()&&Number.isSafeInteger(a.amount)&&a.amount>=0&&a.amount<=10000000000))))}
let loadError=false;try{const raw=localStorage.getItem(key);if(raw){const parsed=JSON.parse(raw);if(!validState(parsed))throw Error('invalid');state=parsed}}catch(e){loadError=true}
const now=new Date();$('#month').value=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');
const month=()=>$('#month').value;
const blank=()=>({days:0,projects:[],milestones:[],note:'',paid:false});
const record=id=>state.months[month()]?.[id]||blank();
const amounts=r=>{const base=Math.round(r.days*10000),bonus=[...r.projects,...r.milestones].reduce((n,a)=>n+a.amount,0);return{base,bonus,total:base+bonus}};
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',3500)}
function save(next){try{localStorage.setItem(key,JSON.stringify(next));state=next;loadError=false;render();return true}catch(e){toast('保存失败：请检查浏览器存储空间或隐私设置');return false}}
function render(){const stats=state.members.reduce((a,m)=>{const r=record(m.id),v=amounts(r);a.total+=v.total;a.base+=v.base;a.bonus+=v.bonus;a.paid+=r.paid?1:0;return a},{total:0,base:0,bonus:0,paid:0});for(const k of ['total','base','bonus'])$('#'+k).textContent=money(stats[k]);$('#count').innerHTML=state.members.length+' <em>人</em>';$('#paidCount').textContent=stats.paid+' 人已发放';const query=$('#search').value.trim().toLowerCase();const list=state.members.filter(m=>(m.name.toLowerCase().includes(query)||m.phone.includes(query))&&(view==='members'||$('#filter').value==='all'||record(m.id).paid===($('#filter').value==='paid')));$('#filter').hidden=view==='members';$('#title').textContent=view==='members'?'成员管理':'工资工作台';$('#subtitle').textContent=view==='members'?'集中管理成员资料，让每次发薪更从容。':'把每一份贡献，清晰地记在薪册里。';$('#listTitle').textContent=view==='members'?'全部成员':'本月工资明细';$('#resultCount').textContent='共 '+list.length+' 位成员';$('#thead').innerHTML='<tr>'+(view==='members'?['成员','电话号码','身份证号','银行卡号','操作']:['成员','有效天数','基础工资','奖励合计','应发工资','发放状态','操作']).map(t=>'<th>'+t+'</th>').join('')+'</tr>';$('#rows').innerHTML=list.map(m=>{const r=record(m.id),v=amounts(r);const person='<td><div class="person"><span class="avatar">'+escapeHTML(m.name.slice(0,1))+'</span><div><strong>'+escapeHTML(m.name)+'</strong><small>'+escapeHTML(m.phone||'未填写电话')+'</small></div></div></td>';return '<tr>'+person+(view==='members'?'<td>'+escapeHTML(m.phone||'—')+'</td><td>'+escapeHTML(mask(m.identity,4))+'</td><td>'+escapeHTML(mask(m.bank,4))+'</td>':'<td>'+r.days+' 天</td><td>'+money(v.base)+'</td><td>'+money(v.bonus)+'</td><td><strong>'+money(v.total)+'</strong></td><td><span class="status '+(r.paid?'paid':'')+'">'+(r.paid?'已发放':'待发放')+'</span></td>')+'<td><button class="link" data-edit="'+escapeHTML(m.id)+'">编辑</button>'+(view==='payroll'?'<button class="link" data-pdf="'+escapeHTML(m.id)+'">PDF ↓</button>':'')+'</td></tr>'}).join('');$('#empty').hidden=list.length>0;if(!state.members.length){$('#empty h3').textContent='从第一位成员开始';$('#empty p').textContent='添加成员资料，录入工作天数和奖励，即可生成工资明细。';$('#emptyAdd').hidden=false}else{$('#empty h3').textContent='没有匹配的成员';$('#empty p').textContent='试试其他关键词或发放状态。';$('#emptyAdd').hidden=true}$('.table-wrap').hidden=!list.length;$('#exportAll').disabled=!state.members.length}
function mask(s,n){return s?s.length>n?'•••• '+s.slice(-n):s:'未填写'}
function rewardRow(target,item={name:'',amount:0}){const row=document.createElement('div');row.className='reward-row';row.innerHTML='<input aria-label="奖励名称" maxlength="200" placeholder="'+(target==='projects'?'项目名称':'重要贡献')+'" required value="'+escapeHTML(item.name)+'"><input aria-label="奖励金额" type="number" min="0" max="100000000" step="0.01" required value="'+item.amount/100+'"><button type="button" aria-label="删除奖励">×</button>';row.querySelector('button').onclick=()=>{row.remove();preview()};$('#'+target).append(row)}
function readRewards(target){return [...$('#'+target).children].map(row=>({name:row.children[0].value.trim(),amount:Math.round(Number(row.children[1].value)*100)}))}
function readSalary(){const f=$('#memberForm').elements;return{days:Number(f.days.value),projects:readRewards('projects'),milestones:readRewards('milestones'),note:f.note.value.trim(),paid:f.paid.checked}}
function preview(){const v=amounts(readSalary());$('#basePreview').textContent=money(v.base);$('#sumPreview').textContent=money(v.total)}
function openEditor(id=null){editing=id;const m=state.members.find(m=>m.id===id),r=id?record(id):blank(),f=$('#memberForm');f.reset();for(const k of ['name','phone','identity','bank','receiverBank','routing','accountName'])f.elements[k].value=m?.[k]||'';fillTemplateMember(f);f.elements.days.value=r.days;f.elements.note.value=r.note;f.elements.paid.checked=r.paid;$('#projects').replaceChildren();$('#milestones').replaceChildren();r.projects.forEach(a=>rewardRow('projects',a));r.milestones.forEach(a=>rewardRow('milestones',a));$('#editorTitle').textContent=m?'编辑 · '+m.name:'添加成员';$('#editorMonth').textContent=month();$('#delete').hidden=!m;preview();$('#editor').showModal()}
$('#memberForm').addEventListener('input',preview);
$('#memberForm').onsubmit=e=>{e.preventDefault();if(loadError&&!confirm('本地记录读取异常。保存将覆盖原有记录，是否继续？'))return;const f=e.target.elements,id=editing||('m-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)),m={id,name:f.name.value.trim(),phone:f.phone.value.trim(),identity:f.identity.value.trim(),bank:f.bank.value.trim(),receiverBank:f.receiverBank.value.trim(),routing:f.routing.value.trim(),accountName:f.accountName.value.trim()},r=readSalary();if(!m.name||[...r.projects,...r.milestones].some(a=>!a.name)){toast('请填写姓名及奖励名称');return}const next=JSON.parse(JSON.stringify(state));const index=next.members.findIndex(a=>a.id===id);if(index<0)next.members.push(m);else next.members[index]=m;next.months[month()]??={};next.months[month()][id]=r;if(!validState(next)){toast('请检查录入的天数和奖励金额');return}if(save(next)){$('#editor').close();toast('成员资料和本月工资已保存')}};
for(const s of ['#add','#emptyAdd'])$(s).onclick=()=>openEditor();for(const s of ['#close','#cancel'])$(s).onclick=()=>$('#editor').close();$('#addProject').onclick=()=>rewardRow('projects');$('#addMilestone').onclick=()=>rewardRow('milestones');$('#delete').onclick=()=>{if(!confirm('删除此成员及所有月份的工资记录？此操作无法撤销。'))return;const next=JSON.parse(JSON.stringify(state));next.members=next.members.filter(m=>m.id!==editing);for(const records of Object.values(next.months))delete records[editing];if(save(next)){$('#editor').close();toast('成员已删除')}};
$('#month').onchange=()=>{if(!month())$('#month').value=now.getFullYear()+'-'+String(now.getMonth()+1).padStart(2,'0');render()};$('#search').oninput=render;$('#filter').onchange=render;document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===b));render()});$('#rows').onclick=e=>{const edit=e.target.closest('[data-edit]'),pdf=e.target.closest('[data-pdf]');if(edit)openEditor(edit.dataset.edit);if(pdf)exportPDF([state.members.find(m=>m.id===pdf.dataset.pdf)])};
function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
$('#backup').onclick=()=>{if(loadError){toast('本地数据读取异常，暂不能生成有效备份');return}download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'薪册备份-'+month()+'.json');toast('备份已导出，请妥善保管成员资料')};$('#restore').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20000000)throw Error();const next=JSON.parse(await file.text());if(!validState(next))throw Error();if(confirm('导入 '+next.members.length+' 位成员的备份？将替换当前浏览器的全部工资记录。')){if(save(next))toast('备份恢复成功')}}catch(e){toast('导入失败：请选择有效的薪册 JSON 备份')}finally{$('#importFile').value=''}};
// Rasterized Chinese text keeps exported PDFs independent of external fonts and services.
function salaryPages(member){const r=record(member.id),v=amounts(r),pages=[];let canvas,ctx,y,page=0;const W=1240,H=1754,margin=100;function text(s,x,z,size=24,color='#334a40'){ctx.fillStyle=color;ctx.font=size+'px "Microsoft YaHei", "PingFang SC", sans-serif';ctx.fillText(s,x,z)}function begin(){canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#edf4ef';ctx.fillRect(0,0,W,260);text('薪册  /  工资明细',margin,95,24,'#607969');text(member.name,margin,173,48,'#28543d');text(month()+' · '+(r.paid?'已发放':'待发放'),margin,220,23,'#607969');y=320;page++}function finish(){text('薪册 · '+month()+' · '+member.name,margin,H-90,18,'#8b9a90');text('第 '+page+' 页',W-200,H-90,18,'#8b9a90');pages.push(canvas.toDataURL('image/jpeg',0.94))}function room(h){if(y+h>H-160){finish();begin()}}function wrap(s,maxWidth,size=24){ctx.font=size+'px "Microsoft YaHei", "PingFang SC", sans-serif';let lines=[],line='';for(const c of String(s)){if(c==='\n'){lines.push(line);line='';continue}if(ctx.measureText(line+c).width>maxWidth&&line){lines.push(line);line=c}else line+=c}lines.push(line);return lines}function row(label,value){const lines=wrap(label,720);for(let i=0;i<lines.length;i++){room(50);text(lines[i],margin,y);if(i===0){const width=ctx.measureText(value).width;text(value,W-margin-width,y)}y+=40}ctx.strokeStyle='#e7eee8';ctx.beginPath();ctx.moveTo(margin,y-15);ctx.lineTo(W-margin,y-15);ctx.stroke();y+=15}function section(s){room(95);y+=20;text(s,margin,y,27,'#28543d');y+=55}begin();row('电话号码',member.phone||'未填写');row('银行卡号',mask(member.bank,4));section('01  基础工资');row(r.days+' 天 × ¥100 / 天',money(v.base));section('02  项目奖励');if(!r.projects.length)row('本月无项目奖励',money(0));r.projects.forEach(a=>row(a.name,money(a.amount)));section('03  里程碑额外奖励');if(!r.milestones.length)row('本月无里程碑奖励',money(0));r.milestones.forEach(a=>row(a.name,money(a.amount)));room(140);y+=20;ctx.fillStyle='#edf4ef';ctx.fillRect(margin,y,W-margin*2,105);text('本月应发合计',margin+25,y+65,28);const sum=money(v.total);ctx.font='38px "Microsoft YaHei", sans-serif';text(sum,W-margin-25-ctx.measureText(sum).width,y+67,38,'#28543d');y+=150;if(r.note){section('备注');for(const line of wrap(r.note,W-margin*2,22)){room(38);text(line,margin,y,22,'#718277');y+=36}}finish();return pages}
function makePDF(images){const enc=new TextEncoder(),parts=[],offsets=[0];let length=0;function push(s){const bytes=typeof s==='string'?enc.encode(s):s;parts.push(bytes);length+=bytes.length}function object(id,body){offsets[id]=length;push(id+' 0 obj\n');push(body);push('\nendobj\n')}push('%PDF-1.4\n');object(1,'<< /Type /Catalog /Pages 2 0 R >>');object(2,'<< /Type /Pages /Count '+images.length+' /Kids ['+images.map((_,i)=>(3+i*3)+' 0 R').join(' ')+'] >>');images.forEach((url,i)=>{const page=3+i*3,img=page+1,content=page+2,raw=atob(url.split(',')[1]),bytes=Uint8Array.from(raw,c=>c.charCodeAt(0));object(page,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /XObject << /Im0 '+img+' 0 R >> >> /Contents '+content+' 0 R >>');offsets[img]=length;push(img+' 0 obj\n<< /Type /XObject /Subtype /Image /Width 1240 /Height 1754 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length '+bytes.length+' >>\nstream\n');push(bytes);push('\nendstream\nendobj\n');const stream='q\n595.28 0 0 841.89 0 0 cm\n/Im0 Do\nQ\n';object(content,'<< /Length '+enc.encode(stream).length+' >>\nstream\n'+stream+'endstream')});const start=length;push('xref\n0 '+offsets.length+'\n0000000000 65535 f \n');for(let i=1;i<offsets.length;i++)push(String(offsets[i]).padStart(10,'0')+' 00000 n \n');push('trailer\n<< /Size '+offsets.length+' /Root 1 0 R >>\nstartxref\n'+start+'\n%%EOF');return new Blob(parts,{type:'application/pdf'})}
async function exportPDF(members){if(!members.length)return;$('#exportAll').disabled=true;toast('正在生成工资明细…');try{await document.fonts.ready;const images=[];for(const m of members){images.push(...salaryPages(m));await new Promise(resolve=>setTimeout(resolve,0))}download(makePDF(images),month()+'-'+(members.length===1?members[0].name.replace(/[\\/:*?"<>|]/g,'_'):'全部成员')+'-工资明细.pdf');toast('PDF 已导出，共 '+members.length+' 位成员')}catch(e){console.error(e);toast('PDF 导出失败，请重试')}finally{render()}}
$('#exportAll').onclick=()=>exportPDF(state.members);initBankExport();render();if(loadError)toast('本地数据读取异常，原始记录未覆盖。可尝试导入备份。');
